import type { Hero, Lang } from '../types'

export const heroes: Record<Lang, Hero[]> = {
  ua: [
    {
      id: 'musician',
      name: 'Олег «Дон Кіхот» Грабар',
      role: 'Музикант · Телепродюсер · Оператор дронів',
      description: 'Митець, музикант і військовий. Війна змусила його заново відповісти на питання, хто він і заради чого творить. Через мистецтво він переосмислює пережите та шукає нові сенси, нову мову й нову опору.',
      quote: '«Музика не зникла. Вона стала способом зберігати себе.»',
      youtubeId: 'ORS1Oh_iRV0',
      youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      episodeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      photo: '/hero-grabar.webp',
    },
    {
      id: 'artist',
      name: 'Павло «Капелан» Вишебаба',
      role: 'Поет · Музикант · Мінометник',
      description: 'Військовий, поет і один із найпомітніших голосів сучасної української культури. Його особистий шлях відображає трансформацію цілого покоління українців, які відкривають власну ідентичність через досвід війни.',
      quote: '«Моя поезія народжується не всупереч війні. Вона народжується всередині неї.»',
      youtubeId: 'j697xh6tXsU',
      youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      episodeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      photo: '/hero-vyshebaba.webp',
    },
    {
      id: 'actor',
      name: 'Станіслав «Ткач» Ткачов',
      role: 'Оператор-постановник · Діджей · Сержант роти БПЛА',
      description: 'Військовий, оператор і музикант. Разом із побратимами з кіноіндустрії він знайшов своє місце на війні, не втративши творчого голосу та здатності бачити людину навіть у найскладніших обставинах.',
      quote: '«До війни я дивився на світ через об\'єктив камери. Тепер — через камери безпілотників.»',
      youtubeId: '0Z0vQ_mbXqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      episodeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      photo: '/hero-tkach.webp',
    },
    {
      id: 'poet',
      name: 'Олена Білозерська',
      role: 'Журналістка · Письменниця · Художниця · Офіцерка ЗСУ',
      description: 'Журналістка, письменниця, художниця та військова. Багато років вона документує українську війну зсередини, поєднуючи роль свідка, учасниці та хранительки пам\'яті.',
      quote: '«Я створюю портрети загиблих, щоб повернути їм ім\'я, обличчя, особисту історію.»',
      youtubeId: '-3geo8Gjy5o',
      youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      episodeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      photo: '/hero-olena.webp',
      season: 1,
    },
    {
      id: 's2-herasymyuk',
      name: 'Олена Герасим\'\u044eк',
      role: 'Поетка · Культурна діячка · Ветеранка',
      description: 'Поезія, Майдан, «Госпітальєри», ветеранський досвід і «Недописані». Історія про слово, яке перестає бути просто текстом і стає дією, пам\'\u044fттю та відповідальністю.',
      quote: '«Слово перестає бути просто текстом — воно стає дією.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-kozub',
      name: 'Тарас Козуб',
      role: 'Лірник · Майстер · Ветеран',
      description: 'Після втрати руки на війні лірник і ветеран Тарас Козуб стає актором і виходить на сцену. У театрі й музиці він знаходить новий сенс, поєднуючи особистий досвід з українською лірницькою традицією.',
      quote: '«Театр дав мені нове життя — мову цією людям, які можуть просто не чути його.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-pravylnyi',
      name: 'Міша Правильний',
      role: 'Репер · Письменник · Військовослужбовець',
      description: 'Репер і військовий розбирає власний шлях зросійщення у книзі, музиці та виставі «Додому». Історія свідомого повернення до мови, культури та власної країни.',
      quote: '«Моя музика — це дорога до себе назад.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-zhadan',
      name: 'Сергій Жадан',
      role: 'Письменник · Поет · Музикант · Військовослужбовець',
      description: 'Харків, Старобільськ, «Хартія», молоді художники та пам\'\u044fть про землю, до якої неможливо повернутися. Історія про культуру, яка допомагає не втратити дім.',
      quote: '«Харків — це не просто місто. Це мова та пам\'\u044fть.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
  ],
  en: [
    {
      id: 'musician',
      name: 'Oleh "Don Quixote" Grabar',
      role: 'Musician · TV Producer · Drone Operator',
      description: 'Artist, musician and soldier. War forced him to answer anew who he is and what he creates for. Through art, he rethinks his experience and seeks new meanings, a new language and a new foundation.',
      quote: '"Music did not disappear. It became a way to preserve myself."',
      youtubeId: 'ORS1Oh_iRV0',
      youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      episodeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      photo: '/hero-grabar.webp',
    },
    {
      id: 'artist',
      name: 'Pavlo "Kapelan" Vyshebaba',
      role: 'Poet · Musician · Mortar Gunner',
      description: 'Soldier, poet and one of the most prominent voices in contemporary Ukrainian culture. His personal journey reflects the transformation of an entire generation of Ukrainians discovering their identity through the experience of war.',
      quote: '"My poetry is not born despite the war. It is born within it."',
      youtubeId: 'j697xh6tXsU',
      youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      episodeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      photo: '/hero-vyshebaba.webp',
    },
    {
      id: 'actor',
      name: 'Stanislav "Tkach" Tkachov',
      role: 'Cinematographer · DJ · UAV Sergeant',
      description: 'Soldier, cinematographer and musician. Together with fellow filmmakers, he found his place in war without losing his creative voice and ability to see people even in the most difficult circumstances.',
      quote: '"Before the war I looked at the world through a camera lens. Now — through drone cameras."',
      youtubeId: '0Z0vQ_mbXqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      episodeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      photo: '/hero-tkach.webp',
    },
    {
      id: 'poet',
      name: 'Olena Bilozerska',
      role: 'Journalist · Writer · Artist · Officer of the Armed Forces',
      description: 'Journalist, writer, artist and soldier. For many years she has been documenting the Ukrainian war from the inside, combining the roles of witness, participant and keeper of memory.',
      quote: '"I create portraits of the fallen to return their name, face and personal story."',
      youtubeId: '-3geo8Gjy5o',
      youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      episodeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      photo: '/hero-olena.webp',
      season: 1,
    },
    {
      id: 's2-herasymyuk',
      name: 'Olena Herasymyuk',
      role: 'Poet · Cultural figure · Veteran',
      description: 'Poetry, Maidan, Hospitallers, veteran experience and "Unfinished". A story about a word that ceases to be mere text and becomes action, memory and responsibility.',
      quote: '"The word stops being just text — it becomes action."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-kozub',
      name: 'Taras Kozub',
      role: 'Lirnik · Master · Veteran',
      description: 'After losing his arm in war, lirnik and veteran Taras Kozub becomes an actor and takes the stage. In theatre and music he finds new meaning, combining personal experience with the Ukrainian lirnik and kobzar tradition.',
      quote: '"Theatre gave me a new life — a language for people who simply cannot feel it."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-pravylnyi',
      name: 'Misha Pravylnyi',
      role: 'Rapper · Writer · Serviceman',
      description: 'Rapper and soldier unpacks his own path of Russification in a book, music and the show "Home". A story of conscious return to language, culture and one\'s own country.',
      quote: '"My music is a road back to myself."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-zhadan',
      name: 'Serhiy Zhadan',
      role: 'Writer · Poet · Musician · Serviceman',
      description: 'Kharkiv, Starobilsk, Khartiya, young artists and the memory of land to which one cannot return. A story about culture that helps not to lose home.',
      quote: '"Kharkiv is not just a city. It is language and memory."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
  ],
}
