import type { Lang, Season } from '../types'

export const seasons: Record<Lang, Season[]> = {
  ua: [
    {
      id: 'season1',
      label: 'Сезон 1',
      episodes: [
        {
          id: 's1e1',
          number: 1,
          title: 'ВОДА',
          synopsis: 'Коли війна змушує заново відповісти на питання: хто ти і заради чого твориш.',
          description: 'До війни його життя було пов\'язане з музикою, творчими проєктами та телебаченням. Сьогодні він керує бойовими операціями безпілотних систем і відповідає за життя своїх побратимів. Але навіть на війні музика не зникла з його життя. Вона стала способом зберігати себе — способом не втратити зв\'язок із тим, ким він був і ким залишається.',
          thumbnail: '/series/water.webp',
          youtubeId: 'ORS1Oh_iRV0',
          youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: false,
          featured: true,
        },
        {
          id: 's1e2',
          number: 2,
          title: 'ВОГОНЬ',
          synopsis: 'Шлях до себе через силу слова, вибір і нову ідентичність.',
          description: 'Павло Вишебаба став одним із голосів української війни. Його вірші перекладають різними мовами світу, його тексти цитують тисячі людей. Але за межами сцени існує інший Павло — військовий, який разом із побратимами виконує бойові завдання на фронті. Між поезією та війною. Між творчістю та необхідністю захищати.',
          thumbnail: '/series/fire.webp',
          youtubeId: 'j697xh6tXsU',
          youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 's1e3',
          number: 3,
          title: 'ПОВІТРЯ',
          synopsis: 'Погляд на людину там, де інші бачать лише війну.',
          description: 'До війни він дивився на світ через об\'єктив камери. Сьогодні він дивиться на поле бою через камери безпілотників. Його професія змінилася — але не змінилася головна риса: здатність бачити більше, бачити далі, бачити те, що залишається непомітним для інших.',
          thumbnail: '/series/air.webp',
          youtubeId: '0Z0vQ_mbXqA',
          youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 's1e4',
          number: 4,
          title: 'ЗЕМЛЯ',
          synopsis: 'Пам\'ять, що тримає зв\'язок між минулим і майбутнім.',
          description: 'Вона документувала події як журналістка. Воювала як доброволиця. Командувала підрозділом як офіцерка. Створювала мистецтво як художниця. Під час зйомок вперше стала матір\'ю. Олена Білозерська — одна з тих постатей, через які можна простежити всю історію сучасної війни України.',
          thumbnail: '/series/earth.webp',
          youtubeId: '-3geo8Gjy5o',
          youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
      ],
    },
    {
      id: 'season2',
      label: 'Сезон 2',
      episodes: [
        {
          id: 's2e1',
          number: 1,
          title: 'ОЛЕНА ГЕРАСИМ\'ЮК',
          synopsis: 'Слово, що стає дією',
          description:
            'Поезія, Майдан, «Госпітальєри», ветеранський досвід і «Недописані». Історія про слово, яке перестає бути просто текстом і стає дією, пам\'яттю та відповідальністю.',
          thumbnail: '/series/s2e1.webp',
          youtubeId: 'w4Yez-dv_4Y',
          youtubeUrl: 'https://www.youtube.com/watch?v=w4Yez-dv_4Y',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: false,
        },
        {
          id: 's2e2',
          number: 2,
          title: 'ТАРАС КОЗУБ',
          synopsis: 'Ліра, що знаходить нову форму',
          description:
            'Після втрати руки на війні лірник і ветеран Тарас Козуб стає актором і виходить на сцену. У театрі й музиці він знаходить новий сенс, поєднуючи особистий досвід з українською лірницькою та кобзарською традицією.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e3',
          number: 3,
          title: 'МІША ПРАВИЛЬНИЙ',
          synopsis: 'Дорога додому',
          description:
            'Репер і військовий розбирає власний шлях зросійщення у книзі, музиці та виставі «Додому». Історія свідомого повернення до мови, культури та власної країни.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e4',
          number: 4,
          title: 'СЕРГІЙ ЖАДАН',
          synopsis: 'Харків і земля, яку неможливо втратити',
          description:
            'Харків, Старобільськ, «Хартія», молоді художники та пам\'ять про землю, до якої неможливо повернутися. Історія про культуру, яка допомагає не втратити дім.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
      ],
    },
    {
      id: 'specials',
      label: 'Спецпроєкти',
      episodes: [
        {
          id: 'ua-special-1',
          number: 1,
          title: 'ЗА КАДРОМ — Епізод I: «ВОДА»',
          synopsis: 'Бекстейдж створення епізоду «ВОДА».',
          youtubeId: 'TQlE-dXAO-w',
          youtubeUrl: 'https://www.youtube.com/watch?v=TQlE-dXAO-w',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
        {
          id: 'ua-special-2',
          number: 2,
          title: 'ЗА КАДРОМ — Епізод II: «ВОГОНЬ»',
          synopsis: 'Бекстейдж створення епізоду «ВОГОНЬ».',
          youtubeId: 'qXmvc2vNNyA',
          youtubeUrl: 'https://www.youtube.com/watch?v=qXmvc2vNNyA',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
        {
          id: 'ua-special-3',
          number: 3,
          title: 'ЗА КАДРОМ — Епізод I: «ВОДА» (версія 2)',
          synopsis: 'Додатковий ролик із плейлиста «За кадром».',
          youtubeId: 'LOlJLaOFey4',
          youtubeUrl: 'https://www.youtube.com/watch?v=LOlJLaOFey4',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
      ],
    },
    {
      id: 'shorts',
      label: 'Shorts',
      episodes: [
        {
          id: 'ua-short-1',
          number: 1,
          title: 'Мій батько народився у ГУЛАГі. Історія, написана кров\'ю',
          synopsis: 'Історія пам\'яті, родини та української ідентичності.',
          youtubeId: 'K240AiXgQx0',
          youtubeUrl: 'https://www.youtube.com/shorts/K240AiXgQx0',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
        {
          id: 'ua-short-2',
          number: 2,
          title: 'Олена Герасим\'юк — Честь',
          synopsis: 'Короткий поетичний фрагмент із голосом героїні.',
          youtubeId: 'Im-PxqL_6o8',
          youtubeUrl: 'https://www.youtube.com/shorts/Im-PxqL_6o8',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
      ],
    },
  ],
  en: [
    {
      id: 'season1',
      label: 'Season 1',
      episodes: [
        {
          id: 's1e1',
          number: 1,
          title: 'WATER',
          synopsis: 'When war forces you to answer anew: who are you and what do you create for.',
          description: 'Before the war, his life was tied to music, creative projects and television. Today he commands drone combat operations and is responsible for the lives of his comrades. But even in war, music has not left his life. It became a way to preserve himself — a way not to lose touch with who he was and who he remains.',
          youtubeId: '8Tj0YHD9Pvk',
          youtubeUrl: 'https://www.youtube.com/watch?v=8Tj0YHD9Pvk',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: true,
          featured: true,
        },
        {
          id: 's1e2',
          number: 2,
          title: 'FIRE',
          synopsis: 'The path to oneself through the power of words, choice, and new identity.',
          description: 'Pavlo Vyshebaba has become one of the voices of the Ukrainian war. His poems are translated into many languages, his texts are quoted by thousands. But behind the stage is another Pavlo — a soldier who carries out combat missions at the front. Between poetry and war. Between creativity and the necessity to defend.',
          youtubeId: 'mppOk7vM2Eo',
          youtubeUrl: 'https://www.youtube.com/watch?v=mppOk7vM2Eo',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: true,
        },
        {
          id: 's1e3',
          number: 3,
          title: 'AIR',
          synopsis: 'A look at the person where others see only war.',
          description: 'Before the war he looked at the world through a camera lens. Today he looks at the battlefield through drone cameras. His profession has changed — but not his defining trait: the ability to see more, see further, see what remains invisible to others.',
          youtubeId: 'cXPqVuA9qHM',
          youtubeUrl: 'https://www.youtube.com/watch?v=cXPqVuA9qHM',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: true,
        },
        {
          id: 's1e4',
          number: 4,
          title: 'EARTH',
          synopsis: 'Memory that holds the connection between past and future.',
          description: 'She documented events as a journalist. Fought as a volunteer. Commanded a unit as an officer. Created art as an artist. During filming, she became a mother for the first time. Olena Bilozerska is one of those figures through whom the entire history of modern Ukraine\'s war can be traced.',
          youtubeId: '-3geo8Gjy5o',
          youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: true,
        },
      ],
    },
    {
      id: 'season2', label: 'Season 2', episodes: [
        {
          id: 's2e1',
          number: 1,
          title: 'OLENA HERASYMYUK',
          synopsis: 'The word that becomes action',
          description:
            'Poetry, Maidan, Hospitallers, veteran experience and "Unfinished". A story about a word that ceases to be mere text and becomes action, memory and responsibility.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e2',
          number: 2,
          title: 'TARAS KOZUB',
          synopsis: 'The lyre that finds a new form',
          description:
            'After losing his arm in war, lirnik and veteran Taras Kozub becomes an actor and takes the stage. In theatre and music he finds new meaning, combining personal experience with the Ukrainian lirnik and kobzar tradition.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e3',
          number: 3,
          title: 'MISHA PRAVYLNYI',
          synopsis: 'The road home',
          description:
            'Rapper and soldier unpacks his own path of Russification in a book, music and the show "Home". A story of conscious return to language, culture and one\'s own country.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e4',
          number: 4,
          title: 'SERHIY ZHADAN',
          synopsis: 'Kharkiv and the land that cannot be lost',
          description:
            'Kharkiv, Starobilsk, Khartiya, young artists and the memory of land to which one cannot return. A story about culture that helps not to lose home.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
      ]
    },
    { id: 'specials', label: 'Specials', episodes: [] },
    {
      id: 'shorts',
      label: 'Shorts',
      episodes: [
        {
          id: 'en-short-1',
          number: 1,
          title: 'I Train to Bring My Friend Home Alive',
          synopsis: 'A story about discipline, friendship and responsibility in wartime.',
          youtubeId: '9ollh8blEBU',
          youtubeUrl: 'https://www.youtube.com/shorts/9ollh8blEBU',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 'en-short-2',
          number: 2,
          title: 'Grew Up in Russian Culture. Then I Chose Ukraine.',
          synopsis: 'A personal turn toward identity, language and belonging.',
          youtubeId: 'Cw5nQo_GS2I',
          youtubeUrl: 'https://www.youtube.com/shorts/Cw5nQo_GS2I',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 'en-short-3',
          number: 3,
          title: 'You Think You Understand War Through a Screen. But You Don\'t.',
          synopsis: 'What distance hides and proximity reveals.',
          youtubeId: 'SLAHS6w893A',
          youtubeUrl: 'https://www.youtube.com/shorts/SLAHS6w893A',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 'en-short-4',
          number: 4,
          title: 'Why Modern War Suddenly Needs Cinematographers',
          synopsis: 'Inside the digital battlefield and new frontline skills.',
          youtubeId: 'Un6CfiiCS8Q',
          youtubeUrl: 'https://www.youtube.com/shorts/Un6CfiiCS8Q',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 'en-short-5',
          number: 5,
          title: 'The Animals No One Talks About',
          synopsis: 'The silent suffering behind every war story.',
          youtubeId: 'V0JxzN-0FpA',
          youtubeUrl: 'https://www.youtube.com/shorts/V0JxzN-0FpA',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 'en-short-6',
          number: 6,
          title: 'What Do Filmmakers and Soldiers Have in Common?',
          synopsis: 'A short reflection on precision, focus and purpose.',
          youtubeId: 'vQFKSEAzbMc',
          youtubeUrl: 'https://www.youtube.com/shorts/vQFKSEAzbMc',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
      ],
    },
  ],
}
