export const ui = {
  ua: {
    nav: {
      series: 'Серії',
      heroes: 'Герої',
      production: 'Виробництво',
      team: 'Команда',
      watch: 'Дивитися',
    },
    hero: {
      title: 'НОВИЙ КОД',
      brandPrefix: 'Новий',
      brandSuffix: 'коd',
      subtitle: 'Авторський документальний проєкт про покоління війни,\nяке формує культуру, пам\'ять та сенси майбутнього.\n\nОсобисті історії українських військових, які залишаються митцями.',
      note: 'Створено за підтримки Українського культурного фонду',
      watchSeries: 'Дивитися серії',
      watchEn: 'Watch in English',
      audioDesc: 'Доступно з тифлокоментарем',
      enAvail: 'English version available',
      scroll: 'Прокрутити вниз',
    },
    sections: {
      series: 'Серії',
      allSeries: 'Усі серії →',
      heroes: 'Герої проєкту',
      allHeroes: 'Усі герої →',
      production: 'Виробництво',
      team: 'Команда',
      partners: 'Партнери',
      accessibility: 'Інклюзивність',
      about: 'Про проєкт',
      press: 'Преса',
      pressSubtitle: 'Історії проєкту «Новий коd_» виходять за межі екрану — у медіа, публічні розмови та міжнародний культурний простір.',
      pressKit: 'Завантажити прескіт',
      pressKitLabel: 'Прес-матеріали для медіа',
      pressContact: 'Контакт: info@newcode.com.ua',
      screenings: 'Покази',
      screeningsUpdate: 'Розклад оновлюється',
      screeningsDescription: '«Новий коd_» можна побачити онлайн та на спеціальних показах. Стежте за анонсами або запросіть проєкт до свого міста, фестивалю чи події.',
      screeningsInvite: 'Запросити проєкт',
      contacts: 'Контакти',
      season2: 'Сезон 2',
      s2BehindScenes: 'Сезон 2 — За лаштунками',
    },
    episode: {
      watch: 'Дивитися',
      details: 'Докладніше',
      audioDesc: 'Тифлокоментар',
      english: 'English',
      subtitles: 'Субтитри',
      featured: 'Актуальне',
      comingSoon: 'Скоро',
      episodeComingSoon: 'Серія вже скоро',
      season2Date: 'Сезон 2 — вересень 2026',
    },
    episode_modal: {
      watch: 'Дивитися на YouTube →',
      close: 'Закрити',
    },
    hero_modal: {
      watchEpisode: 'Дивитися серію →',
      close: 'Закрити',
      episodeComingSoon: 'Серія скоро',
      season2ComingSoon: 'Вже скоро — сезон 2',
    },
    accessibility: {
      title: 'Доступність',
      description: '«Новий коd_» має бути доступним кожному — незалежно від способу сприйняття та мови.',
      audioDescTitle: 'Тифлокоментар',
      audioDescItems: ['Сезон 1', 'Сезон 2'],
      enTitle: 'Англомовна версія',
      enItems: ['Дубляж (Сезон 1)', 'Субтитри (Сезон 2)'],
      watchBtn: 'Дивитися доступні версії',
    },
    about: {
      title: 'Про проєкт',
      importanceTitle: 'Важливість',
      manifesto: 'Нова Україна народжується зараз. Це покоління, яке одночасно воює і творить, захищає і переосмислює — і формує нову культуру, нову пам\'ять та нові сенси просто зараз, поки все це відбувається на наших очах.',
      paragraphs: [
        '«Новий коd_» — авторський цикл документальних фільмів про українських військових, які були митцями у мирному житті та не втратили здатності творити під час війни. Проєкт створений режисеркою та журналісткою Мариною Чанковою за підтримки Українського культурного фонду та партнерів.',
        'У центрі кожної історії — людина. Не герой із плаката. Не символ. А жива людина зі своїми страхами, сумнівами, втратами, надіями та внутрішніми змінами. Кожен герой проживає власний шлях трансформації.',
        'Ми спостерігаємо, як музикант стає командиром дронів, поет працює на мінометній позиції, кінооператор керує безпілотними системами, а художниця поєднує військову службу з материнством і творчістю.',
      ],
      importance: 'Культура під час війни — це не розкіш. Це спосіб вижити. Нові тексти пишуться між бойовими виходами. Нова музика народжується в бліндажах. Нові картини створюються на фронті. Ми переконані, що культура є такою ж важливою частиною національної стійкості, як армія, дипломатія чи економіка.',
      text: '«Новий коd_» — авторський цикл документальних фільмів про українських військових, які були митцями у мирному житті та не втратили здатності творити під час війни.',
    },
    contact: {
      title: 'Контакти',
      email: 'novyikod.ua@gmail.com',
      phone: '+38 (050) 430 44 15',
      namePlaceholder: 'Ваше ім\'я',
      emailPlaceholder: 'Ваш email',
      messagePlaceholder: 'Повідомлення',
      submit: 'Надіслати',
      subscribe: 'Підписатися',
      subscribePlaceholder: 'Ваш email',
      successMessage: 'Дякуємо! Ми звяжемося.',
    },
    production: {
      s2Description: 'Між сценою і фронтом. Між репетицією та бойовим виходом. Між камерою і реальним життям.',
      blocks: [
        { label: 'Географія', text: 'Зйомки відбувалися в різних регіонах України. Перший сезон — Київщина, Харківщина, Донеччина. Другий сезон розширює географію: Харків, Київ, Львів, Івано-Франківськ. Камера заходить у творчі майстерні й радіостудії, виходить на театральні та концертні сцени.' },
        { label: 'Метод', text: 'Документальне спостереження без постановочних сцен. Камера залишається поруч з людиною в її реальному середовищі, фіксуючи тишу, сумнів і момент внутрішнього вибору.' },
        { label: 'Команда', text: 'Незалежна авторська команда документалістів, операторів, журналістів, звукорежисерів та продюсерів з досвідом виробництва воєнних, гуманітарних та культурних проєктів.' },
        { label: 'Довіра', text: 'Основою проєкту стала довіра. Робота над кожним героєм тривала від кількох тижнів до кількох місяців. Саме завдяки цій довірі команда могла бути поруч у найважливіші моменти.' },
      ],
    },
    footer: {
      title: 'Новий коd',
      rights: 'Новий коd_. Усі права захищені.',
    },
  },
  en: {
    nav: {
      series: 'Series',
      heroes: 'Heroes',
      production: 'Production',
      team: 'Team',
      watch: 'Watch',
    },
    hero: {
      title: 'NEW CODE',
      brandPrefix: 'New',
      brandSuffix: 'code',
      subtitle: 'An authored documentary project about a generation of war\nthat shapes culture, memory and the meanings of the future.\n\nPersonal stories of Ukrainian servicemen who remain artists.',
      note: 'Created with the support of the Ukrainian Cultural Fund',
      watchSeries: 'Watch Series',
      watchEn: 'Watch in English',
      audioDesc: 'Audio description available',
      enAvail: 'English version available',
      scroll: 'Scroll down',
    },
    sections: {
      series: 'Series',
      allSeries: 'All Series →',
      heroes: 'Project Heroes',
      allHeroes: 'All Heroes →',
      production: 'Production',
      team: 'Team',
      partners: 'Partners',
      accessibility: 'Accessibility',
      about: 'About',
      press: 'Press',
      pressSubtitle: 'The stories of “New Code” go beyond the screen — into media, public conversations and international cultural space.',
      pressKit: 'Download Press Kit',
      pressKitLabel: 'Press materials for media',
      pressContact: 'Contact: info@newcode.com.ua',
      screenings: 'Screenings',
      screeningsUpdate: 'Schedule updating',
      screeningsDescription: '"New Code" can be seen online and at special screenings. Follow the announcements or invite the project to your city, festival or event.',
      screeningsInvite: 'Invite the project',
      contacts: 'Contact',
      season2: 'Season 2',
      s2BehindScenes: 'Season 2 — Behind the Scenes',
    },
    episode: {
      watch: 'Watch',
      details: 'More details',
      audioDesc: 'Audio Description',
      english: 'English',
      subtitles: 'Subtitles',
      featured: 'Featured',
      comingSoon: 'Coming soon',
      episodeComingSoon: 'Episode coming soon',
      season2Date: 'Season 2 — September 2026',
    },
    episode_modal: {
      watch: 'Watch on YouTube →',
      close: 'Close',
    },
    hero_modal: {
      watchEpisode: 'Watch Episode →',
      close: 'Close',
      episodeComingSoon: 'Episode coming soon',
      season2ComingSoon: 'Season 2 — coming soon',
    },
    accessibility: {
      title: 'Accessibility',
      description: '"New Code" should be accessible to everyone — regardless of the way of perception and language.',
      audioDescTitle: 'Audio Description',
      audioDescItems: ['Season 1', 'Season 2'],
      enTitle: 'English Version',
      enItems: ['Dubbing (Season 1)', 'Subtitles (Season 2)'],
      watchBtn: 'Watch accessible versions',
    },
    about: {
      title: 'About the Project',
      importanceTitle: 'Why It Matters',
      manifesto: 'A new Ukraine is being born right now. This is a generation that simultaneously fights and creates, defends and reimagines — shaping new culture, new memory and new meaning as it all unfolds before our eyes.',
      paragraphs: [
        '"New Code" is an authored cycle of documentary films about Ukrainian servicemen who were artists in peacetime and have not lost their ability to create during the war. The project was created by documentary filmmaker and journalist Maryna Chankova, supported by the Ukrainian Cultural Fund and partners.',
        'At the centre of each story is a real person — not a poster hero, not a symbol. A living person with their own fears, doubts, losses, hopes and inner changes. Every hero lives through their own path of transformation.',
        'We observe how a musician becomes a drone unit commander, a poet works at a mortar position, a cinematographer operates unmanned systems, and an artist combines military service with motherhood and creativity.',
      ],
      importance: 'Culture in wartime is not a luxury. It is a way to survive. New texts are written between combat missions. New music is born in dugouts. New paintings are created at the front. We believe that culture is as important a part of national resilience as the army, diplomacy or economy.',
      text: '"New Code" is an authored cycle of documentary films about Ukrainian servicemen who were artists in peacetime and have not lost their ability to create during the war.',
    },
    contact: {
      title: 'Contact',
      email: 'novyikod.ua@gmail.com',
      phone: '+38 (050) 430 44 15',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'Your email',
      messagePlaceholder: 'Message',
      submit: 'Send',
      subscribe: 'Subscribe',
      subscribePlaceholder: 'Your email',
      successMessage: "Thank you! We'll be in touch.",
    },
    production: {
      s2Description: 'Between stage and frontline. Between rehearsal and combat. Between the camera and real life.',
      blocks: [
        { label: 'Geography', text: 'Filming took place across different regions of Ukraine. Season 1 covers Kyiv, Kharkiv and Donetsk regions. Season 2 expands the geography: Kharkiv, Kyiv, Lviv and Ivano-Frankivsk. The camera enters creative workshops and radio studios, takes the stage at theatres and concerts.' },
        { label: 'Method', text: 'Observational documentary without staged scenes. The camera stays with the person in their real environment, capturing silence, doubt and the moment of inner choice.' },
        { label: 'Team', text: 'An independent creative team of documentary filmmakers, cinematographers, journalists and producers with experience in conflict, humanitarian and cultural projects.' },
        { label: 'Trust', text: 'The foundation of the project was trust. Work with each hero lasted from several weeks to several months. This trust allowed the team to be present in the most important moments.' },
      ],
    },
    footer: {
      title: 'New code',
      rights: 'New Code. All rights reserved.',
    },
  },
}
