import type { Hero, Lang, PressItem, Screening, Season, TeamMember } from './types'

// ─── Social links ────────────────────────────────────────────────────────────
export const YOUTUBE_URL = 'https://www.youtube.com/@NovyiKod'
export const YOUTUBE_URL_EN = 'https://www.youtube.com/@NovyiKod'

// ─── Partners ────────────────────────────────────────────────────────────────
export const partners = {
  ua: [
    { name: 'Український культурний фонд', abbr: 'УКФ' },
    { name: '3-тя окрема штурмова бригада', abbr: '3 ОШБр' },
    { name: 'ТОВ «Авіокон проєкт»', abbr: 'Авіокон' },
  ],
  en: [
    { name: 'Ukrainian Cultural Fund', abbr: 'UCF' },
    { name: '3rd Separate Assault Brigade', abbr: '3 SAB' },
    { name: 'Aviokon Project', abbr: 'Aviokon' },
  ],
}

// ─── Live / Featured ────────────────────────────────────────────────────────

export const liveContent = {
  ua: {
    label: 'Актуальне',
    title: '«Новий коd_». Сезон 2 — вже у вересні 2026!',
    description:
      'Сергій Жадан, Олена Герасим\'юк, Тарас Козуб і Міша Правильний — герої другого сезону «Нового коdу_». Події розгортаються у Києві, Харкові, Львові та Івано-Франківську, а історії героїв сягають окупованого Донбасу. Це розповідь про пам\'ять і повернення додому, досвід військовослужбовців і ветеранів — та українську культуру, яка під час війни вистоює, змінюється й народжує нові форми та сенси.',
    youtubeId: 'nSXbKjmJ2RY',
    comingSoon: false,
    watchUrl: 'https://www.youtube.com/watch?v=nSXbKjmJ2RY',
    watchLabel: 'Дивитися трейлер',
    ytLabel: 'На YouTube',
  },
  en: {
    label: 'Coming Soon',
    title: '"New Code". Season 2 — September 2026!',
    description:
      'Serhiy Zhadan, Olena Herasymyuk, Taras Kozub and Misha Pravylnyi — the heroes of the second season of "New Code". Events unfold in Kyiv, Kharkiv, Lviv and Ivano-Frankivsk, and the heroes\' stories reach occupied Donbas. This is a story about memory and returning home, the experience of servicemen and veterans — and Ukrainian culture that endures, transforms and creates new forms and meanings during war.',
    youtubeId: 'nSXbKjmJ2RY',
    comingSoon: false,
    watchUrl: 'https://www.youtube.com/watch?v=nSXbKjmJ2RY',
    watchLabel: 'Watch Trailer',
    ytLabel: 'On YouTube',
  },
}

// ─── Series ─────────────────────────────────────────────────────────────────

export const seasons: Record<Lang, Season[]> = {
  ua: [
    {
      id: 'season1',
      label: 'Сезон 1',
      episodes: [
        {
          id: 's1e1',
          number: 1,
          title: 'ВОДА',
          synopsis: 'Коли війна змушує заново відповісти на питання: хто ти і заради чого твориш.',
          description: 'До війни його життя було пов\'язане з музикою, творчими проєктами та телебаченням. Сьогодні він керує бойовими операціями безпілотних систем і відповідає за життя своїх побратимів. Але навіть на війні музика не зникла з його життя. Вона стала способом зберігати себе — способом не втратити зв\'язок із тим, ким він був і ким залишається.',
          thumbnail: '/series/water.webp',
          youtubeId: 'ORS1Oh_iRV0',
          youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: false,
          featured: true,
        },
        {
          id: 's1e2',
          number: 2,
          title: 'ВОГОНЬ',
          synopsis: 'Шлях до себе через силу слова, вибір і нову ідентичність.',
          description: 'Павло Вишебаба став одним із голосів української війни. Його вірші перекладають різними мовами світу, його тексти цитують тисячі людей. Але за межами сцени існує інший Павло — військовий, який разом із побратимами виконує бойові завдання на фронті. Між поезією та війною. Між творчістю та необхідністю захищати.',
          thumbnail: '/series/fire.webp',
          youtubeId: 'j697xh6tXsU',
          youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 's1e3',
          number: 3,
          title: 'ПОВІТРЯ',
          synopsis: 'Погляд на людину там, де інші бачать лише війну.',
          description: 'До війни він дивився на світ через об\'єктив камери. Сьогодні він дивиться на поле бою через камери безпілотників. Його професія змінилася — але не змінилася головна риса: здатність бачити більше, бачити далі, бачити те, що залишається непомітним для інших.',
          thumbnail: '/series/air.webp',
          youtubeId: '0Z0vQ_mbXqA',
          youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: false,
        },
        {
          id: 's1e4',
          number: 4,
          title: 'ЗЕМЛЯ',
          synopsis: 'Пам\'ять, що тримає зв\'язок між минулим і майбутнім.',
          description: 'Вона документувала події як журналістка. Воювала як доброволиця. Командувала підрозділом як офіцерка. Створювала мистецтво як художниця. Під час зйомок вперше стала матір\'ю. Олена Білозерська — одна з тих постатей, через які можна простежити всю історію сучасної війни України.',
          thumbnail: '/series/earth.webp',
          youtubeId: '-3geo8Gjy5o',
          youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
        },
      ],
    },
    {
      id: 'season2',
      label: 'Сезон 2',
      episodes: [
        {
          id: 's2e1',
          number: 1,
          title: 'ОЛЕНА ГЕРАСИМ\'ЮК',
          synopsis: 'Слово, що стає дією',
          description:
            'Поезія, Майдан, «Госпітальєри», ветеранський досвід і «Недописані». Історія про слово, яке перестає бути просто текстом і стає дією, пам\'яттю та відповідальністю.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e2',
          number: 2,
          title: 'ТАРАС КОЗУБ',
          synopsis: 'Ліра, що знаходить нову форму',
          description:
            'Після втрати руки на війні лірник і ветеран Тарас Козуб стає актором і виходить на сцену. У театрі й музиці він знаходить новий сенс, поєднуючи особистий досвід з українською лірницькою та кобзарською традицією.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e3',
          number: 3,
          title: 'МІША ПРАВИЛЬНИЙ',
          synopsis: 'Дорога додому',
          description:
            'Репер і військовий розбирає власний шлях зросійщення у книзі, музиці та виставі «Додому». Історія свідомого повернення до мови, культури та власної країни.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e4',
          number: 4,
          title: 'СЕРГІЙ ЖАДАН',
          synopsis: 'Харків і земля, яку неможливо втратити',
          description:
            'Харків, Старобільськ, «Хартія», молоді художники та пам\'ять про землю, до якої неможливо повернутися. Історія про культуру, яка допомагає не втратити дім.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
      ],
    },
    {
      id: 'specials',
      label: 'Спецпроєкти',
      episodes: [],
    },
    {
      id: 'shorts',
      label: 'Shorts',
      episodes: [],
    },
  ],
  en: [
    {
      id: 'season1',
      label: 'Season 1',
      episodes: [
        {
          id: 's1e1',
          number: 1,
          title: 'WATER',
          synopsis: 'When war forces you to answer anew: who are you and what do you create for.',
          description: 'Before the war, his life was tied to music, creative projects and television. Today he commands drone combat operations and is responsible for the lives of his comrades. But even in war, music has not left his life. It became a way to preserve himself — a way not to lose touch with who he was and who he remains.',
          youtubeId: 'ORS1Oh_iRV0',
          youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: true,
          featured: true,
        },
        {
          id: 's1e2',
          number: 2,
          title: 'FIRE',
          synopsis: 'The path to oneself through the power of words, choice, and new identity.',
          description: 'Pavlo Vyshebaba has become one of the voices of the Ukrainian war. His poems are translated into many languages, his texts are quoted by thousands. But behind the stage is another Pavlo — a soldier who carries out combat missions at the front. Between poetry and war. Between creativity and the necessity to defend.',
          youtubeId: 'j697xh6tXsU',
          youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
          hasAudioDesc: true,
          hasEnglish: true,
          hasSubtitles: true,
        },
        {
          id: 's1e3',
          number: 3,
          title: 'AIR',
          synopsis: 'A look at the person where others see only war.',
          description: 'Before the war he looked at the world through a camera lens. Today he looks at the battlefield through drone cameras. His profession has changed — but not his defining trait: the ability to see more, see further, see what remains invisible to others.',
          youtubeId: '0Z0vQ_mbXqA',
          youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: true,
        },
        {
          id: 's1e4',
          number: 4,
          title: 'EARTH',
          synopsis: 'Memory that holds the connection between past and future.',
          description: 'She documented events as a journalist. Fought as a volunteer. Commanded a unit as an officer. Created art as an artist. During filming, she became a mother for the first time. Olena Bilozerska is one of those figures through whom the entire history of modern Ukraine\'s war can be traced.',
          youtubeId: '-3geo8Gjy5o',
          youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
          hasAudioDesc: false,
          hasEnglish: true,
          hasSubtitles: true,
        },
      ],
    },
    {
      id: 'season2', label: 'Season 2', episodes: [
        {
          id: 's2e1',
          number: 1,
          title: 'OLENA HERASYMYUK',
          synopsis: 'The word that becomes action',
          description:
            'Poetry, Maidan, Hospitallers, veteran experience and "Unfinished". A story about a word that ceases to be mere text and becomes action, memory and responsibility.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e2',
          number: 2,
          title: 'TARAS KOZUB',
          synopsis: 'The lyre that finds a new form',
          description:
            'After losing his arm in war, lirnik and veteran Taras Kozub becomes an actor and takes the stage. In theatre and music he finds new meaning, combining personal experience with the Ukrainian lirnik and kobzar tradition.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e3',
          number: 3,
          title: 'MISHA PRAVYLNYI',
          synopsis: 'The road home',
          description:
            'Rapper and soldier unpacks his own path of Russification in a book, music and the show "Home". A story of conscious return to language, culture and one\'s own country.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
        {
          id: 's2e4',
          number: 4,
          title: 'SERHIY ZHADAN',
          synopsis: 'Kharkiv and the land that cannot be lost',
          description:
            'Kharkiv, Starobilsk, Khartiya, young artists and the memory of land to which one cannot return. A story about culture that helps not to lose home.',
          youtubeId: '',
          youtubeUrl: '',
          hasAudioDesc: false,
          hasEnglish: false,
          hasSubtitles: false,
          comingSoon: true,
        },
      ]
    },
    { id: 'specials', label: 'Specials', episodes: [] },
    { id: 'shorts', label: 'Shorts', episodes: [] },
  ],
}

// ─── Heroes ─────────────────────────────────────────────────────────────────

export const heroes: Record<Lang, Hero[]> = {
  ua: [
    {
      id: 'musician',
      name: 'Олег «Дон Кіхот» Грабар',
      role: 'Музикант · Телепродюсер · Оператор дронів',
      description: 'Митець, музикант і військовий. Війна змусила його заново відповісти на питання, хто він і заради чого творить. Через мистецтво він переосмислює пережите та шукає нові сенси, нову мову й нову опору.',
      quote: '«Музика не зникла. Вона стала способом зберігати себе.»',
      youtubeId: 'ORS1Oh_iRV0',
      youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      episodeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      photo: '/hero-grabar.webp',
    },
    {
      id: 'artist',
      name: 'Павло «Капелан» Вишебаба',
      role: 'Поет · Музикант · Мінометник',
      description: 'Військовий, поет і один із найпомітніших голосів сучасної української культури. Його особистий шлях відображає трансформацію цілого покоління українців, які відкривають власну ідентичність через досвід війни.',
      quote: '«Моя поезія народжується не всупереч війні. Вона народжується всередині неї.»',
      youtubeId: 'j697xh6tXsU',
      youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      episodeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      photo: '/hero-vyshebaba.webp',
    },
    {
      id: 'actor',
      name: 'Станіслав «Ткач» Ткачев',
      role: 'Оператор-постановник · Діджей · Сержант роти БПЛА',
      description: 'Військовий, оператор і музикант. Разом із побратимами з кіноіндустрії він знайшов своє місце на війні, не втративши творчого голосу та здатності бачити людину навіть у найскладніших обставинах.',
      quote: '«До війни я дивився на світ через об\'єктив камери. Тепер — через камери безпілотників.»',
      youtubeId: '0Z0vQ_mbXqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      episodeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      photo: '/hero-tkach.webp',
    },
    {
      id: 'poet',
      name: 'Олена Білозерська',
      role: 'Журналістка · Письменниця · Художниця · Офіцерка ЗСУ',
      description: 'Журналістка, письменниця, художниця та військова. Багато років вона документує українську війну зсередини, поєднуючи роль свідка, учасниці та хранительки пам\'яті.',
      quote: '«Я створюю портрети загиблих, щоб повернути їм ім\'я, обличчя, особисту історію.»',
      youtubeId: '-3geo8Gjy5o',
      youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      episodeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      photo: '/hero-olena.webp',
      season: 1,
    },
    {
      id: 's2-herasymyuk',
      name: 'Олена Герасим\'\u044eк',
      role: 'Поетка · Культурна діячка · Ветеранка',
      description: 'Поезія, Майдан, «Госпітальєри», ветеранський досвід і «Недописані». Історія про слово, яке перестає бути просто текстом і стає дією, пам\'\u044fттю та відповідальністю.',
      quote: '«Слово перестає бути просто текстом — воно стає дією.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-kozub',
      name: 'Тарас Козуб',
      role: 'Лірник · Майстер · Ветеран',
      description: 'Після втрати руки на війні лірник і ветеран Тарас Козуб стає актором і виходить на сцену. У театрі й музиці він знаходить новий сенс, поєднуючи особистий досвід з українською лірницькою традицією.',
      quote: '«Театр дав мені нове життя — мову цією людям, які можуть просто не чути його.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-pravylnyi',
      name: 'Міша Правильний',
      role: 'Репер · Письменник · Військовослужбовець',
      description: 'Репер і військовий розбирає власний шлях зросійщення у книзі, музиці та виставі «Додому». Історія свідомого повернення до мови, культури та власної країни.',
      quote: '«Моя музика — це дорога до себе назад.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-zhadan',
      name: 'Сергій Жадан',
      role: 'Письменник · Поет · Музикант · Військовослужбовець',
      description: 'Харків, Старобільськ, «Хартія», молоді художники та пам\'\u044fть про землю, до якої неможливо повернутися. Історія про культуру, яка допомагає не втратити дім.',
      quote: '«Харків — це не просто місто. Це мова та пам\'\u044fть.»',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
  ],
  en: [
    {
      id: 'musician',
      name: 'Oleh "Don Quixote" Grabar',
      role: 'Musician · TV Producer · Drone Operator',
      description: 'Artist, musician and soldier. War forced him to answer anew who he is and what he creates for. Through art, he rethinks his experience and seeks new meanings, a new language and a new foundation.',
      quote: '"Music did not disappear. It became a way to preserve myself."',
      youtubeId: 'ORS1Oh_iRV0',
      youtubeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      episodeUrl: 'https://www.youtube.com/watch?v=ORS1Oh_iRV0',
      photo: '/hero-grabar.webp',
    },
    {
      id: 'artist',
      name: 'Pavlo "Kapelan" Vyshebaba',
      role: 'Poet · Musician · Mortar Gunner',
      description: 'Soldier, poet and one of the most prominent voices in contemporary Ukrainian culture. His personal journey reflects the transformation of an entire generation of Ukrainians discovering their identity through the experience of war.',
      quote: '"My poetry is not born despite the war. It is born within it."',
      youtubeId: 'j697xh6tXsU',
      youtubeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      episodeUrl: 'https://www.youtube.com/watch?v=j697xh6tXsU',
      photo: '/hero-vyshebaba.webp',
    },
    {
      id: 'actor',
      name: 'Stanislav "Tkach" Tkachev',
      role: 'Cinematographer · DJ · UAV Sergeant',
      description: 'Soldier, cinematographer and musician. Together with fellow filmmakers, he found his place in war without losing his creative voice and ability to see people even in the most difficult circumstances.',
      quote: '"Before the war I looked at the world through a camera lens. Now — through drone cameras."',
      youtubeId: '0Z0vQ_mbXqA',
      youtubeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      episodeUrl: 'https://www.youtube.com/watch?v=0Z0vQ_mbXqA',
      photo: '/hero-tkach.webp',
    },
    {
      id: 'poet',
      name: 'Olena Bilozerska',
      role: 'Journalist · Writer · Artist · Officer of the Armed Forces',
      description: 'Journalist, writer, artist and soldier. For many years she has been documenting the Ukrainian war from the inside, combining the roles of witness, participant and keeper of memory.',
      quote: '"I create portraits of the fallen to return their name, face and personal story."',
      youtubeId: '-3geo8Gjy5o',
      youtubeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      episodeUrl: 'https://www.youtube.com/watch?v=-3geo8Gjy5o',
      photo: '/hero-olena.webp',
      season: 1,
    },
    {
      id: 's2-herasymyuk',
      name: 'Olena Herasymyuk',
      role: 'Poet · Cultural figure · Veteran',
      description: 'Poetry, Maidan, Hospitallers, veteran experience and "Unfinished". A story about a word that ceases to be mere text and becomes action, memory and responsibility.',
      quote: '"The word stops being just text — it becomes action."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-kozub',
      name: 'Taras Kozub',
      role: 'Lirnik · Master · Veteran',
      description: 'After losing his arm in war, lirnik and veteran Taras Kozub becomes an actor and takes the stage. In theatre and music he finds new meaning, combining personal experience with the Ukrainian lirnik and kobzar tradition.',
      quote: '"Theatre gave me a new life — a language for people who simply cannot feel it."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-pravylnyi',
      name: 'Misha Pravylnyi',
      role: 'Rapper · Writer · Serviceman',
      description: 'Rapper and soldier unpacks his own path of Russification in a book, music and the show "Home". A story of conscious return to language, culture and one\'s own country.',
      quote: '"My music is a road back to myself."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
    {
      id: 's2-zhadan',
      name: 'Serhiy Zhadan',
      role: 'Writer · Poet · Musician · Serviceman',
      description: 'Kharkiv, Starobilsk, Khartiya, young artists and the memory of land to which one cannot return. A story about culture that helps not to lose home.',
      quote: '"Kharkiv is not just a city. It is language and memory."',
      youtubeId: '', youtubeUrl: '', episodeUrl: '', season: 2, comingSoon: true,
    },
  ],
}

// ─── Team ────────────────────────────────────────────────────────────────────

export const team: Record<Lang, { director: { name: string; bio: string; statement: string[] }; members: TeamMember[] }> = {
  ua: {
    director: {
      name: 'Марина Чанкова',
      bio: 'Авторка та режисерка проєкту, документалістка, журналістка та продюсерка з понад п\'ятнадцятирічним досвідом роботи в українських та міжнародних медіа. Співпрацювала з Voice of America, Amnesty International, Bloomberg, Euronews та іншими медіаорганізаціями.',
      statement: [
        'Мене цікавить не лише те, що відбувається з країною під час війни. Мене цікавить, що відбувається з людиною.',
        'Як вона змінюється. Що втрачає. Що знаходить. І як саме народжується нова культура в момент, коли здається, що світ руйнується навколо.',
        'У центрі кожної історії — жива людина зі своїми страхами, сумнівами, втратами, надіями та внутрішніми змінами.',
        'Кожен герой проживає власний шлях трансформації. Ми переконані, що культура є такою ж важливою частиною національної стійкості, як армія, дипломатія чи економіка.',
      ],
    },
    members: [
      { name: 'Антон Печатнов, Артем Терещенко, Станіслав Ткачев, Дмитро Муленко, Дмитро Чуб', role: 'Оператори-постановники' },
      { name: 'Віталій Ляшко, Артем Стромаков, Василь Вишняков', role: 'Монтаж' },
      { name: 'Андрій Танабаш', role: 'Продюсер' },
      { name: 'Дар\'я Чупрун', role: 'Фотографиня' },
      { name: 'Дмитро Чистяков', role: 'Редактор' },
    ],
  },
  en: {
    director: {
      name: 'Maryna Chankova',
      bio: 'Project author and director, documentary filmmaker, journalist and producer with over fifteen years of experience in Ukrainian and international media. Has collaborated with Voice of America, Amnesty International, Bloomberg, Euronews and other media organizations.',
      statement: [
        'I am interested not only in what is happening to the country during the war. I am interested in what is happening to the person.',
        'How they change. What they lose. What they find. And how exactly new culture is born in a moment when the world seems to be falling apart.',
        'At the centre of each story is a real person with their fears, doubts, losses, hopes and inner changes.',
        'Every hero lives through their own path of transformation. We believe that culture is as important a part of national resilience as the army, diplomacy or economy.',
      ],
    },
    members: [
      { name: 'Anton Pechatnov, Artem Tereshchenko, Stanislav Tkachev, Dmytro Mulenko, Dmytro Chub', role: 'Cinematographers' },
      { name: 'Vitaliy Lyashko, Artem Stromakov, Vasyl Vyshniakov', role: 'Editors' },
      { name: 'Andrii Tanabash', role: 'Producer' },
      { name: 'Daria Chuprun', role: 'Photographer' },
      { name: 'Dmytro Chistiakov', role: 'Story Editor' },
    ],
  },
}

// ─── Press ───────────────────────────────────────────────────────────────────

export const press: Record<Lang, PressItem[]> = {
  ua: [
    { outlet: 'Culture Partnership', title: '«Новий код: як війна народжує нову українську культуру»', date: '2025', url: '#' },
    { outlet: 'Detector Media', title: '«B Україні запустили документальний вебсеріал про військових, які поєднують службу і творчість»', date: '2025', url: '#' },
    { outlet: 'Сектор Правди', title: '«Мистецтво як зброя: як війна формує нову українську культуру»', date: '2025', url: '#' },
    { outlet: '04637', title: '«Документальний вебсеріал про військових, які поєднують службу і творчість, запустили в Україні»', date: '2025', url: '#' },
    { outlet: 'Еспресо', title: '«Мілітарна культура: як поети й музиканти воюють за Україну»', date: '2025', url: '#' },
    { outlet: 'Detector Media', title: '«5 листопада — фотовиставка та показ епізодів «Новий коd_»»', date: 'листопад 2025', url: '#' },
    { outlet: 'Львівська міська рада', title: '«Львів\'ян запрошують на фотовиставку та показ «Новий коd_»»', date: 'листопад 2025', url: '#' },
  ],
  en: [
    { outlet: 'Culture Partnership', title: '"New Code: how war gives birth to new Ukrainian culture"', date: '2025', url: '#' },
    { outlet: 'Detector Media', title: '"Ukraine launches documentary web series about soldiers who combine service and creativity"', date: '2025', url: '#' },
    { outlet: 'Sektor Pravdy', title: '"Art as a weapon: how war shapes new Ukrainian culture"', date: '2025', url: '#' },
    { outlet: '04637', title: '"Documentary web series about soldiers combining service and art launched in Ukraine"', date: '2025', url: '#' },
    { outlet: 'Espreso', title: '"Military culture: how poets and musicians fight for Ukraine"', date: '2025', url: '#' },
    { outlet: 'Detector Media', title: '"Nov 5 — photo exhibition and screening of New Code episodes"', date: 'Nov 2025', url: '#' },
    { outlet: 'Lviv City Council', title: '"Lviv residents invited to photo exhibition and screening of New Code"', date: 'Nov 2025', url: '#' },
  ],
}

// ─── Screenings ──────────────────────────────────────────────────────────────

export const screenings: Record<Lang, Screening[]> = {
  ua: [
    {
      title: 'Фотовиставка та показ «Новий коd_»',
      location: 'Будинок Воїна, Львів',
      date: '5 листопада 2025',
    },
  ],
  en: [
    {
      title: 'Photo Exhibition and Screening of “New Code”',
      location: 'Budynok Voina, Lviv',
      date: '5 November 2025',
    },
  ],
}

// ─── Nav / UI strings ────────────────────────────────────────────────────────

export const ui = {
  ua: {
    nav: {
      series: 'Серії',
      heroes: 'Герої',
      production: 'Виробництво',
      team: 'Команда',
      watch: 'Дивитися',
    },
    hero: {
      title: 'НОВИЙ КОД',
      brandPrefix: 'Новий',
      brandSuffix: 'коd',
      subtitle: 'Авторський документальний проєкт про покоління війни,\nяке формує культуру, пам\'ять та сенси майбутнього.\n\nОсобисті історії українських військових, які залишаються митцями.',
      note: 'Створено за підтримки Українського культурного фонду',
      watchSeries: 'Дивитися серії',
      watchEn: 'Watch in English',
      audioDesc: 'Доступно з тифлокоментарем',
      enAvail: 'English version available',
      scroll: 'Прокрутити вниз',
    },
    sections: {
      series: 'Серії',
      allSeries: 'Усі серії →',
      heroes: 'Герої проєкту',
      allHeroes: 'Усі герої →',
      production: 'Виробництво',
      team: 'Команда',
      partners: 'Партнери',
      accessibility: 'Інклюзивність',
      about: 'Про проєкт',
      press: 'Преса',
      pressSubtitle: 'Історії проєкту «Новий коd_» виходять за межі екрану — у медіа, публічні розмови та міжнародний культурний простір.',
      pressKit: 'Завантажити прескіт',
      pressKitLabel: 'Прес-матеріали для медіа',
      pressContact: 'Контакт: info@newcode.com.ua',
      screenings: 'Покази',
      screeningsUpdate: 'Розклад оновлюється',
      screeningsDescription: '«Новий коd_» можна побачити онлайн та на спеціальних показах. Стежте за анонсами або запросіть проєкт до свого міста, фестивалю чи події.',
      screeningsInvite: 'Запросити проєкт',
      contacts: 'Контакти',
      season2: 'Сезон 2',
      s2BehindScenes: 'Сезон 2 — За лаштунками',
    },
    episode: {
      watch: 'Дивитися',
      details: 'Докладніше',
      audioDesc: 'Тифлокоментар',
      english: 'English',
      subtitles: 'Субтитри',
      featured: 'Актуальне',
      comingSoon: 'Скоро',
      episodeComingSoon: 'Серія вже скоро',
      season2Date: 'Сезон 2 — вересень 2026',
    },
    episode_modal: {
      watch: 'Дивитися на YouTube →',
      close: 'Закрити',
    },
    hero_modal: {
      watchEpisode: 'Дивитися серію →',
      close: 'Закрити',
      episodeComingSoon: 'Серія скоро',
      season2ComingSoon: 'Вже скоро — сезон 2',
    },
    accessibility: {
      title: 'Доступність',
      description: '«Новий коd_» має бути доступним кожному — незалежно від способу сприйняття та мови.',
      audioDescTitle: 'Тифлокоментар',
      audioDescItems: ['Сезон 1', 'Сезон 2'],
      enTitle: 'Англомовна версія',
      enItems: ['Дубляж (Сезон 1)', 'Субтитри (Сезон 2)'],
      watchBtn: 'Дивитися доступні версії',
    },
    about: {
      title: 'Про проєкт',
      importanceTitle: 'Важливість',
      manifesto: 'Нова Україна народжується зараз. Це покоління, яке одночасно воює і творить, захищає і переосмислює — і формує нову культуру, нову пам\'ять та нові сенси просто зараз, поки все це відбувається на наших очах.',
      paragraphs: [
        '«Новий коd_» — авторський цикл документальних фільмів про українських військових, які були митцями у мирному житті та не втратили здатності творити під час війни. Проєкт створений режисеркою та журналісткою Мариною Чанковою за підтримки Українського культурного фонду та партнерів.',
        'У центрі кожної історії — людина. Не герой із плаката. Не символ. А жива людина зі своїми страхами, сумнівами, втратами, надіями та внутрішніми змінами. Кожен герой проживає власний шлях трансформації.',
        'Ми спостерігаємо, як музикант стає командиром дронів, поет працює на мінометній позиції, кінооператор керує безпілотними системами, а художниця поєднує військову службу з материнством і творчістю.',
      ],
      importance: 'Культура під час війни — це не розкіш. Це спосіб вижити. Нові тексти пишуться між бойовими виходами. Нова музика народжується в бліндажах. Нові картини створюються на фронті. Ми переконані, що культура є такою ж важливою частиною національної стійкості, як армія, дипломатія чи економіка.',
      text: '«Новий коd_» — авторський цикл документальних фільмів про українських військових, які були митцями у мирному житті та не втратили здатності творити під час війни.',
    },
    contact: {
      title: 'Контакти',
      email: 'novyikod.ua@gmail.com',
      phone: '+38 (050) 430 44 15',
      namePlaceholder: 'Ваше ім\'я',
      emailPlaceholder: 'Ваш email',
      messagePlaceholder: 'Повідомлення',
      submit: 'Надіслати',
      subscribe: 'Підписатися',
      subscribePlaceholder: 'Ваш email',
      successMessage: 'Дякуємо! Ми звяжемося.',
    },
    production: {
      s2Description: 'Між сценою і фронтом. Між репетицією та бойовим виходом. Між камерою і реальним життям.',
      blocks: [
        { label: 'Географія', text: 'Зйомки відбувалися в різних регіонах України. Перший сезон — Київщина, Харківщина, Донеччина. Другий сезон розширює географію: Харків, Київ, Львів, Івано-Франківськ. Камера заходить у творчі майстерні й радіостудії, виходить на театральні та концертні сцени.' },
        { label: 'Метод', text: 'Документальне спостереження без постановочних сцен. Камера залишається поруч з людиною в її реальному середовищі, фіксуючи тишу, сумнів і момент внутрішнього вибору.' },
        { label: 'Команда', text: 'Незалежна авторська команда документалістів, операторів, журналістів, звукорежисерів та продюсерів з досвідом виробництва воєнних, гуманітарних та культурних проєктів.' },
        { label: 'Довіра', text: 'Основою проєкту стала довіра. Робота над кожним героєм тривала від кількох тижнів до кількох місяців. Саме завдяки цій довірі команда могла бути поруч у найважливіші моменти.' },
      ],
    },
    footer: {
      title: 'Новий коd',
      rights: 'Новий коd_. Усі права захищені.',
    },
  },
  en: {
    nav: {
      series: 'Series',
      heroes: 'Heroes',
      production: 'Production',
      team: 'Team',
      watch: 'Watch',
    },
    hero: {
      title: 'NEW CODE',
      brandPrefix: 'New',
      brandSuffix: 'code',
      subtitle: 'An authored documentary project about a generation of war\nthat shapes culture, memory and the meanings of the future.\n\nPersonal stories of Ukrainian servicemen who remain artists.',
      note: 'Created with the support of the Ukrainian Cultural Fund',
      watchSeries: 'Watch Series',
      watchEn: 'Watch in English',
      audioDesc: 'Audio description available',
      enAvail: 'English version available',
      scroll: 'Scroll down',
    },
    sections: {
      series: 'Series',
      allSeries: 'All Series →',
      heroes: 'Project Heroes',
      allHeroes: 'All Heroes →',
      production: 'Production',
      team: 'Team',
      partners: 'Partners',
      accessibility: 'Accessibility',
      about: 'About',
      press: 'Press',
      pressSubtitle: 'The stories of “New Code” go beyond the screen — into media, public conversations and international cultural space.',
      pressKit: 'Download Press Kit',
      pressKitLabel: 'Press materials for media',
      pressContact: 'Contact: info@newcode.com.ua',
      screenings: 'Screenings',
      screeningsUpdate: 'Schedule updating',
      screeningsDescription: '"New Code" can be seen online and at special screenings. Follow the announcements or invite the project to your city, festival or event.',
      screeningsInvite: 'Invite the project',
      contacts: 'Contact',
      season2: 'Season 2',
      s2BehindScenes: 'Season 2 — Behind the Scenes',
    },
    episode: {
      watch: 'Watch',
      details: 'More details',
      audioDesc: 'Audio Description',
      english: 'English',
      subtitles: 'Subtitles',
      featured: 'Featured',
      comingSoon: 'Coming soon',
      episodeComingSoon: 'Episode coming soon',
      season2Date: 'Season 2 — September 2026',
    },
    episode_modal: {
      watch: 'Watch on YouTube →',
      close: 'Close',
    },
    hero_modal: {
      watchEpisode: 'Watch Episode →',
      close: 'Close',
      episodeComingSoon: 'Episode coming soon',
      season2ComingSoon: 'Season 2 — coming soon',
    },
    accessibility: {
      title: 'Accessibility',
      description: '"New Code" should be accessible to everyone — regardless of the way of perception and language.',
      audioDescTitle: 'Audio Description',
      audioDescItems: ['Season 1', 'Season 2'],
      enTitle: 'English Version',
      enItems: ['Dubbing (Season 1)', 'Subtitles (Season 2)'],
      watchBtn: 'Watch accessible versions',
    },
    about: {
      title: 'About the Project',
      importanceTitle: 'Why It Matters',
      manifesto: 'A new Ukraine is being born right now. This is a generation that simultaneously fights and creates, defends and reimagines — shaping new culture, new memory and new meaning as it all unfolds before our eyes.',
      paragraphs: [
        '"New Code" is an authored cycle of documentary films about Ukrainian servicemen who were artists in peacetime and have not lost their ability to create during the war. The project was created by documentary filmmaker and journalist Maryna Chankova, supported by the Ukrainian Cultural Fund and partners.',
        'At the centre of each story is a real person — not a poster hero, not a symbol. A living person with their own fears, doubts, losses, hopes and inner changes. Every hero lives through their own path of transformation.',
        'We observe how a musician becomes a drone unit commander, a poet works at a mortar position, a cinematographer operates unmanned systems, and an artist combines military service with motherhood and creativity.',
      ],
      importance: 'Culture in wartime is not a luxury. It is a way to survive. New texts are written between combat missions. New music is born in dugouts. New paintings are created at the front. We believe that culture is as important a part of national resilience as the army, diplomacy or economy.',
      text: '"New Code" is an authored cycle of documentary films about Ukrainian servicemen who were artists in peacetime and have not lost their ability to create during the war.',
    },
    contact: {
      title: 'Contact',
      email: 'novyikod.ua@gmail.com',
      phone: '+38 (050) 430 44 15',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'Your email',
      messagePlaceholder: 'Message',
      submit: 'Send',
      subscribe: 'Subscribe',
      subscribePlaceholder: 'Your email',
      successMessage: "Thank you! We'll be in touch.",
    },
    production: {
      s2Description: 'Between stage and frontline. Between rehearsal and combat. Between the camera and real life.',
      blocks: [
        { label: 'Geography', text: 'Filming took place across different regions of Ukraine. Season 1 covers Kyiv, Kharkiv and Donetsk regions. Season 2 expands the geography: Kharkiv, Kyiv, Lviv and Ivano-Frankivsk. The camera enters creative workshops and radio studios, takes the stage at theatres and concerts.' },
        { label: 'Method', text: 'Observational documentary without staged scenes. The camera stays with the person in their real environment, capturing silence, doubt and the moment of inner choice.' },
        { label: 'Team', text: 'An independent creative team of documentary filmmakers, cinematographers, journalists and producers with experience in conflict, humanitarian and cultural projects.' },
        { label: 'Trust', text: 'The foundation of the project was trust. Work with each hero lasted from several weeks to several months. This trust allowed the team to be present in the most important moments.' },
      ],
    },
    footer: {
      title: 'New code',
      rights: 'New Code. All rights reserved.',
    },
  },
}
